In [1]:
#Importing libraries
import pandas as pd
import numpy as np

# **Customers Table**

In [165]:
#data
df1=pd.read_csv("olist_customers_dataset.csv")

In [3]:
#Analysing
df1.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [4]:
#size
df1.shape

(99441, 5)

In [5]:
#null values checking
df1.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [6]:
#duplicate values
df1.duplicated().sum()

np.int64(0)

In [7]:
#Removing extra spaces
df1['customer_city'].str.strip()

0                       franca
1        sao bernardo do campo
2                    sao paulo
3              mogi das cruzes
4                     campinas
                 ...
99436                sao paulo
99437          taboao da serra
99438                fortaleza
99439                   canoas
99440                    cotia
Name: customer_city, Length: 99441, dtype: object

In [8]:
#data types
df1.dtypes

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

In [9]:
df1['customer_state'].unique()

array(['SP', 'SC', 'MG', 'PR', 'RJ', 'RS', 'PA', 'GO', 'ES', 'BA', 'MA',
       'MS', 'CE', 'DF', 'RN', 'PE', 'MT', 'AM', 'AP', 'AL', 'RO', 'PB',
       'TO', 'PI', 'AC', 'SE', 'RR'], dtype=object)

# **Sellers Table**

In [11]:
#data
df2=pd.read_csv('olist_sellers_dataset.csv')

In [12]:
#Analysing
df2.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [13]:
#size
df2.shape

(3095, 4)

In [14]:
#data types
df2.dtypes

seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

In [15]:
#Null values
df2.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [16]:
#duplicate values
df2.duplicated().sum()

np.int64(0)

In [18]:
#Identifying special chars in city names
df2['seller_city'].unique()

array(['campinas', 'mogi guacu', 'rio de janeiro', 'sao paulo',
       'braganca paulista', 'brejao', 'penapolis', 'curitiba', 'anapolis',
       'itirapina', 'tubarao', 'lauro de freitas', 'imbituba', 'brasilia',
       'porto seguro', 'guaruja', 'tabatinga', 'salto', 'tres de maio',
       'belo horizonte', 'arapongas', 'sao bernardo do campo', 'tatui',
       'garopaba', 'camanducaia', 'tupa', 'guarulhos',
       'sao jose dos pinhais', 'sao ludgero', 'sao jose', 'piracicaba',
       'porto alegre', 'congonhal', 'santo andre', 'osasco', 'valinhos',
       'joinville', 'saquarema', 'barra velha', 'petropolis',
       'santo antonio da patrulha', 'ponta grossa', 'santana de parnaiba',
       'sao carlos', 'ibitinga', 'barueri', 'caxias do sul', 'araguari',
       'contagem', 'jaragua do sul', 'lages - sc', 'bento goncalves',
       'catanduva', 'ribeirao pires', 'jaboticabal', 'echapora', 'cotia',
       'rio do sul', 'sorocaba', 'pradopolis', 'itaborai', 'mirassol',
       'birigui', 'assis', 'jaguariuna', 'araraquara', 'macae',
       'rio claro', 'londrina', 'ribeirao preto', 'tres coracoes',
       'nhandeara', 'orleans', 'cuiaba', 'formosa do oeste', 'santos',
       'santa terezinha de goias', 'arvorezinha', 'guiricema', 'caruaru',
       'franca', 'salvador', 'diadema', 'itaquaquecetuba',
       'lencois paulista', 'carapicuiba', 'uruacu', 'itajai', 'loanda',
       'maringa', 'ferraz de vasconcelos', 'limeira', 'claudio',
       'niteroi', 'osvaldo cruz', 'sao goncalo', 'jaciara',
       'balenario camboriu', 'timbo', 'jacutinga', 'fortaleza',
       'ferraz de  vasconcelos', 'mirandopolis', 'bauru', 'jacarei',
       'itu', 'laranjeiras do sul', 'videira', 'florianopolis',
       'itapecerica da serra', 'mamanguape', 'ponte nova', 'goioere',
       'pederneiras', 'itapevi', 'goiania', 'campina grande',
       'estancia velha', 'resende', 'maua', 'caratinga', 'auriflama/sp',
       'cafelandia', 'uba', 'sao paulo / sao paulo',
       'sao jose do rio preto', 'porto ferreira', 'tres coroas',
       'blumenau', 'mogi das cruzes', 'jaci', 'laranjal paulista',
       'americana', 'sertanopolis', 'apucarana', 'colombo',
       'vicente de carvalho', 'mesquita', 'sao pauo', 'cascavel',
       'fazenda rio grande', 'taboao da serra', 'sao jose dos campos',
       'toledo', 'marechal candido rondon', 'jundiai', 'mandirituba',
       'suzano', 'vespasiano', 'santa rosa', 'sao joaquim da barra',
       'santo antonio de posse', 'uruguaiana', 'campanha', 'piracanjuba',
       'concordia', 'santa rita do sapucai', 'barretos', 'indaiatuba',
       'nilopolis', 'pompeia', 'barro alto', 'são paulo', 'praia grande',
       'luiz alves', 'brusque', 'criciuma', 'jales', 'atibaia',
       'rio branco', 'barra mansa', 'marilia', 'bahia', 'taubate',
       'cascavael', 'monteiro lobato', 'viana', 'paraiba do sul',
       'mococa', 'sao roque', 'passos', 'francisco beltrao', 'tocantins',
       'porto belo', 'nova iguacu', 'icara', 'lajeado', 'horizontina',
       'votorantim', 'campo bom', 'monte alto', 'fernandopolis',
       'pedreira', 'poa', 'divinopolis', 'santa barbara d´oeste',
       'canoas', 'mombuca', 'sete lagoas', 'campo do meio',
       'cordeiropolis', 'uberlandia', 'santa barbara d oeste',
       'volta redonda', '04482255', 'aracatuba', 'monte siao', 'garuva',
       'bonfinopolis de minas', 'cosmopolis', 'pocos de caldas',
       'artur nogueira', 'joao pessoa', 'dois corregos', 'araquari',
       'novo hamburgo, rio grande do sul, brasil', 'floranopolis',
       'sumare', 'guaira', 'cachoeiro de itapemirim', 'serrana',
       'rolandia', 'congonhas', 'sao  jose dos pinhais', 'boituva',
       'mairipora', 'guaimbe', 'parai', 'aperibe', 'jaguaruna',
       'vila velha', 'juiz de fora', 'fronteira', 'novo horizonte',
       'pilar do sul', 'itajobi', 'cariacica / es', 'prados', 'mucambo',
       'montes claros', 'vicosa', 'porto velho', 'sao jose do rio pardo',
       'pato branco', 'sao joao del rei', 'presidente prudente',
       'paracambi', 'serra negra', 'sao caetano do sul', 'bom jardim',
       'serra redonda', 'sao francisco do sul', 'betim', 'imbituva',
       'guaratuba', 'teresina', "sao miguel d'oeste", 'california',
       'japira', 'foz do iguacu', 'nova friburgo', 'itau de minas',
       'oliveira', 'sabara', 'pedrinhas paulista', 'votuporanga',
       'holambra', 'ararangua', 'pinhais', 'pato bragado', 'carazinho',
       'arinos', 'sao pedro', 'lages', 'ampere', 'itauna', 'mogi mirim',
       'curitibanos', 'brasilia df', 'mogi das cruses', 'hortolandia',
       'ipatinga', 'laguna', 'dores de campos', 'sao paulo - sp',
       'araras', 'divisa nova', 'igaracu do tiete', 'pitangueiras',
       'campo grande', 'garca', 'presidente epitacio', 'sbc/sp',
       "arraial d'ajuda (porto seguro)", 'pacatuba', 'formosa',
       'borda da mata', 'ubatuba', 'entre rios do oeste', 'formiga',
       'venancio aires', 'navegantes', 'cruzeiro', 'santa maria',
       'muriae', 'santo andre/sao paulo', 'ipe', 'messias targino',
       'varginha', 'botucatu', 'domingos martins', 'uberaba',
       'coronel fabriciano', 'cachoeirinha', 's jose do rio preto',
       'taruma', 'pirassununga', 'aruja', 'sp / sp', 'angra dos reis',
       'juzeiro do norte', 'laurentino', 'flores da cunha', 'montenegro',
       'pedregulho', 'novo hamburgo', 'torres', 'aracaju',
       'santa catarina', 'joao pinheiro', 'bady bassitt', 'sinop',
       'guarapuava', 'araucaria', 'vitoria', 'batatais', 'lagoa santa',
       'chapeco', 'umuarama', 'belford roxo', 'cariacica',
       'monte alegre do sul', 'sp', 'lagoa da prata', 'rolante',
       'teresopolis', 'itaporanga', 'campo largo', 'sao joao de meriti',
       'maua/sao paulo', 'bom jesus dos perdoes', 'brotas', 'irece',
       'coxim', 'jau', 'conselheiro lafaiete', 'amparo',
       'sao miguel do oeste', 'gaspar', 'rio bonito', 'mandaguari',
       'vargem grande paulista', 'conchal', 'cambe', 'marialva',
       'alfenas', 'balneario camboriu', 'palhoca', 'sao bernardo do capo',
       'guara', 'colatina', 'franco da rocha', 'lambari',
       'mogi das cruzes / sp', 'treze tilias',
       'rio de janeiro \\rio de janeiro', 'paulo lopes', 'santa cecilia',
       'braco do norte', 'floresta', 'farroupilha', 'castro', 'luziania',
       'joao monlevade', 'pelotas', 'sao bento', 'campos dos goytacazes',
       'ouro fino', 'sao jose dos pinhas', 'tiete', 'viamao', 'janauba',
       'capivari', 'santa terezinha de itaipu', 'igrejinha',
       'sao bento do sul', 'duque de caxias', 'araxa', 'canoinhas',
       'recife', 'barbacena/ minas gerais', 'vera cruz', 'parnamirim',
       'santo angelo', 'paincandu', 'tres rios', 'tanabi',
       'portoferreira', 'itatiba', 'sarandi', 'cravinhos', 'morrinhos',
       'bebedouro', 'almirante tamandare', 'bertioga', 'natal',
       'belo horizont', 'ivoti', 'andira-pr', 'cerqueira cesar',
       'marapoama', 'imigrante', 'mairinque', 'sao paulo sp',
       'rio de janeiro / rio de janeiro', 'andradas', 'sando andre',
       'nova odessa', 'paulinia', 'extrema', 'olimpia',
       'angra dos reis rj', 'ronda alta', 'sao  paulo', 'sao vicente',
       'pinhais/pr', 'portao', 'registro', 'ao bernardo do campo',
       'carmo do cajuru', 'embu das artes', 'fernando prestes',
       'castro pires', 'vargem grande do sul', 'campina das missoes',
       'sao pedro da aldeia', 'miguelopolis', 'itapui', 'sbc', 'neopolis',
       'mineiros do tiete', 'varzea paulista', 'nova lima', 'barbacena',
       'caieiras', 'buritama', 'erechim', 'itapetininga', 'pinhalzinho',
       'descalvado', 'pitanga', 'bage', 'taio', "santa barbara d'oeste",
       'patos de minas', 'garulhos', 'jarinu', 'nova petropolis',
       'ribeirao preto / sao paulo', 'camboriu', 'nova trento',
       'sao luis', 'sao jose do rio pret', 'eusebio', 'itaipulandia',
       'ipira', 'campo magro', 'tiradentes', 'sao paluo', 'baependi',
       'embu guacu', 'paraiso do sul', 'aparecida', 'cataguases',
       'bariri', 'abadia de goias', 'alambari', 'ji parana', 'vassouras',
       'lorena', 'rodeio', 'louveira', 'guanhaes',
       'santo antonio de padua', 'presidente getulio', 'campos novos',
       'eunapolis', 'engenheiro coelho', 'rio das pedras',
       'afonso claudio', 'carapicuiba / sao paulo', 'centro', 'parana',
       'indaial', 'bombinhas', 'orlandia', 'itapeva', 'sao sebastiao',
       'macatuba', 'sao joao da boa vista', 'teixeira soares',
       'mandaguacu', 'rio do oeste', 'vendas@creditparts.com.br',
       'armacao dos buzios', 'mateus leme', 'sao paulop',
       'campo limpo paulista', 'socorro', 'serra', 'bocaiuva do sul',
       'ilheus', 'imbe', 'soledade', 'cajamar', 'rio negrinho',
       'clementina', 'francisco morato', 'rio grande', 'xaxim', 'manaus',
       'terra boa', 'minas gerais', 'avare', 'ibirite',
       'santa maria da serra', 'auriflama', 'condor', 'ibia', 'guanambi',
       'caucaia', 'cordilheira alta', 'carmo da mata', 'ouro preto',
       'pedro leopoldo', 'santa rosa de viterbo', 'xanxere',
       'alvares machado', 'scao jose do rio pardo', 'ribeirao das neves',
       'medianeira', 'massaranduba', 'cornelio procopio', 'pirituba',
       'jambeiro', 'sao leopoldo', 'aguas claras df', 'ribeirao pretp',
       'cianorte', 'feira de santana', 'cachoeira do sul', 'guariba',
       'sao sebastiao da grama/sp', 'dracena', 'ourinhos',
       'robeirao preto', 'cacador', 'gama', 'queimados', 'cananeia',
       'presidente bernardes', 'pinhalao', 'sombrio', 'campo mourao',
       'ilicinea', 'itabira', 'barrinha', 'jussara', 'uniao da vitoria',
       'triunfo', 'santa cruz do sul', 'colorado', 'itapema', 'sapiranga',
       'paranavai', 'alvorada', 'ipaussu', 'rio verde', 'mage',
       'tabao da serra', 'bofete', 'picarras', 'marica', 'jaragua',
       'governador valadares', 'rio de janeiro, rio de janeiro, brasil',
       'pouso alegre', 'timoteo', 'muqui', 'ipua', 'jacarei / sao paulo',
       'varzea alegre', 'guaratingueta', 'tambau', 'irati',
       'riberao preto', 'aparecida de goiania', 'bandeirantes',
       'vitoria de santo antao', 'palotina', 'leme'], dtype=object)

In [20]:
#Removing unnecssary chars like //
df2['seller_city']=df2['seller_city'].str.replace(r'[\\/]+','/',regex=True)

# **Geolocation Table**

In [21]:
#data
df3=pd.read_csv('olist_geolocation_dataset.csv')

In [22]:
#Analysing
df3.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [24]:
#data types
df3.dtypes

geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

In [25]:
#Null values
df3.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [166]:
#checking duplicates wrt long and lat
df3[['geolocation_lat','geolocation_lng']].duplicated().sum()

np.int64(0)

In [35]:
df3.head(1000161)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
...,...,...,...,...,...
1000156,99950,-28.072188,-52.011272,tapejara,RS
1000157,99950,-28.068864,-52.012964,tapejara,RS
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS

In [46]:
#getting info about the rows which have same lat and long(999802 is the row where we get true when we are checking duplicates)
print(repr(df3.loc[999802, 'geolocation_lat']))
print(repr(df3.loc[999802, 'geolocation_lng']))

np.float64(-27.87712511771236)
np.float64(-52.22488216264145)

In [45]:
#checking whether all the cols of duplicated row(lat,long) are same
df3[(df3['geolocation_lat']==-27.87712511771236) & (df3['geolocation_lng']==-52.22488216264145)]

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
999802,99900,-27.877125,-52.224882,getulio vargas,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS

In [48]:
#removing the duplicates and keeping only the one row
df3=df3.drop_duplicates(
    subset=['geolocation_lat','geolocation_lng'],
    keep='first'
)

In [51]:
#nearly 2k rows are removed
df3.shape

(718463, 5)

# **Payments Table**

In [52]:
#data
df4=pd.read_csv('olist_order_payments_dataset.csv')

In [53]:
#size
df4.shape

(103886, 5)

In [54]:
#Analysing
df4.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [56]:
#duplicate rows
df4.duplicated().sum()

np.int64(0)

In [57]:
#Null values
df4.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [59]:
#checking not defined values in payment tyep
df4['payment_type'].unique()

array(['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined'],
      dtype=object)

In [71]:
#checking whether payment_sequential col have incorrect values like 0
df4[df4['payment_sequential']==0]

Empty DataFrame
Columns: [order_id, payment_sequential, payment_type, payment_installments, payment_value]
Index: []

In [72]:
#checking whether the paymnet val is -ve or 0
df4[df4['payment_value']<=0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
19922,8bcbe01d44d147f901cd3192671144db,4,voucher,1,0.0
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.0
43744,6ccb433e00daae1283ccc956189c82ae,4,voucher,1,0.0
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
62674,45ed6e85398a87c253db47c2d9f48216,3,voucher,1,0.0
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0
100766,b23878b3e8eb4d25a158f57d96331b18,4,voucher,1,0.0

In [76]:
#we have payments with 0 val..but in that we have payment_seq as 1 and >1 thatmeans >1 orders have other payments also ..so verifyng it
df4[df4['order_id']=='fa65dad1b0e818e3ccc5cb0e39231352'].sort_values(by='payment_sequential')
#we have other payments for the order ids having pay_seq>1 and pay_val=0..so that pay_seq payment may be cancelled due to some reason..so we do not remove that order ids from payment table as they are valid only

,order_id,payment_sequential,payment_type,payment_installments,payment_value
14321,fa65dad1b0e818e3ccc5cb0e39231352,1,voucher,1,3.71
23074,fa65dad1b0e818e3ccc5cb0e39231352,2,voucher,1,8.51
65641,fa65dad1b0e818e3ccc5cb0e39231352,3,voucher,1,2.95
9985,fa65dad1b0e818e3ccc5cb0e39231352,4,voucher,1,29.16
28330,fa65dad1b0e818e3ccc5cb0e39231352,5,voucher,1,0.66
29648,fa65dad1b0e818e3ccc5cb0e39231352,6,voucher,1,5.02
82593,fa65dad1b0e818e3ccc5cb0e39231352,7,voucher,1,0.32
68853,fa65dad1b0e818e3ccc5cb0e39231352,8,voucher,1,26.02
17274,fa65dad1b0e818e3ccc5cb0e39231352,9,voucher,1,1.08
19565,fa65dad1b0e818e3ccc5cb0e39231352,10,voucher,1,12.86
32519,fa65dad1b0e818e3ccc5cb0e39231352,11,voucher,1,4.03
73537,fa65dad1b0e818e3ccc5cb0e39231352,12,voucher,1,3.60
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.00
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.00
63369,fa65dad1b0e818e3ccc5cb0e39231352,15,voucher,1,14.04
78050,fa65dad1b0e818e3ccc5cb0e39231352,16,voucher,1,12.86
79670,fa65dad1b0e818e3ccc5cb0e39231352,17,voucher,1,3.72
80321,fa65dad1b0e818e3ccc5cb0e39231352,18,voucher,1,0.73
74721,fa65dad1b0e818e3ccc5cb0e39231352,19,voucher,1,5.02
93337,fa65dad1b0e818e3ccc5cb0e39231352,20,voucher,1,150.00
74239,fa65dad1b0e818e3ccc5cb0e39231352,21,voucher,1,4.11
100606,fa65dad1b0e818e3ccc5cb0e39231352,22,voucher,1,4.03
85166,fa65dad1b0e818e3ccc5cb0e39231352,23,voucher,1,18.86
99213,fa65dad1b0e818e3ccc5cb0e39231352,24,voucher,1,0.42
24879,fa65dad1b0e818e3ccc5cb0e39231352,25,voucher,1,3.68
79587,fa65dad1b0e818e3ccc5cb0e39231352,26,voucher,1,28.27
4885,fa65dad1b0e818e3ccc5cb0e39231352,27,voucher,1,66.02
39111,fa65dad1b0e818e3ccc5cb0e39231352,28,voucher,1,29.05
39108,fa65dad1b0e818e3ccc5cb0e39231352,29,voucher,1,19.26

In [80]:
#checking do we have more orders who have made more than 20+ payments
df4['payment_sequential'].value_counts().sort_index()

payment_sequential
1     99360
2      3039
3       581
4       278
5       170
6       118
7        82
8        54
9        43
10       34
11       29
12       21
13       13
14       10
15        8
16        6
17        6
18        6
19        6
20        4
21        4
22        3
23        2
24        2
25        2
26        2
27        1
28        1
29        1
Name: count, dtype: int64

In [83]:
#we have payments 0 orders..in that the 2nd type is payment_seq as 1..so checking whether they have any orders more
df4[df4['order_id']=='c8c528189310eaa44a745b8d9d26908b']

,order_id,payment_sequential,payment_type,payment_installments,payment_value
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0

# **Orders Table**

In [84]:
#data(we need to check that payment_seq=1 and pay_val=0 orders ids exist in orders table thats why imported this data)
df5=pd.read_csv('olist_orders_dataset.csv')

In [89]:
#checking the 3 order ids with pay_val=0 and pay_seq =1 and whith no further orders exist in orders table
df5[df5['order_id'].isin([
    'c8c528189310eaa44a745b8d9d26908b',
    '4637ca194b6387e2d538dc89b124b0ee',
    '00b1cb0320190ca0daa2c88b35206009'
])]
#they are in orders table but they are cancelled so no need to remove them from payments table as they are valid order ids that are cancelled orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
1130,00b1cb0320190ca0daa2c88b35206009,3532ba38a3fd242259a514ac2b6ae6b6,canceled,2018-08-28 15:26:39,NaN,NaN,NaN,2018-09-12 00:00:00
39919,4637ca194b6387e2d538dc89b124b0ee,a73c1f73f5772cf801434bf984b0b1a7,canceled,2018-09-03 14:14:25,NaN,NaN,NaN,2018-09-10 00:00:00
40235,c8c528189310eaa44a745b8d9d26908b,197a2a6a77da93f678ea0d379f21da0a,canceled,2018-08-28 20:05:14,NaN,NaN,NaN,2018-09-11 00:00:00

In [85]:
#Analysing
df5.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [90]:
#Null values
df5.isnull().sum()
#no prblm if we have null values in order_approved_at,order_delivered_carrier_date,order_delivered_customer_date..bcoz they are may be cancelled orders

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [91]:
#duplicates
df5.duplicated().sum()

np.int64(0)

In [93]:
#data types
df5.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [92]:
#size
df5.shape

(99441, 8)

In [94]:
#changing the date cols from object to datetime
date_cols=[
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]
df5[date_cols]=df5[date_cols].apply(pd.to_datetime)

In [95]:
#checking datatypes again
df5.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [171]:
#checking chronological order of the dates
invalid1=df5[
    (df5['order_delivered_carrier_date'].notna()) &
    (df5['order_delivered_customer_date'].notna()) &
    (df5['order_delivered_carrier_date']>df5['order_delivered_customer_date'])
]

invalid2=df5[
    (df5['order_purchase_timestamp'].notna()) &
    (df5['order_approved_at'].notna()) &
    (df5['order_purchase_timestamp']>df5['order_approved_at'])
]

invalid3=df5[
    (df5['order_delivered_carrier_date'].notna()) &
    (df5['order_approved_at'].notna()) &
    (df5['order_approved_at']>df5['order_delivered_carrier_date'])
]

print("purchased > approved invalid orders = ",len(invalid2),
     "\napproved > carrier invalid orders = ",len(invalid3),
     "\ncarrier > delivery invalid orders = ",len(invalid1)
     )
#res = we can change the dates...may be they are wrongly entered bcoz they have to be get from diffrent sysytems like seller,courier,buyer ... and also Not deleting anything because they did not make any diff while calc yearly or monthly orders among 1,00,000 orders

purchased > approved invalid orders =  0
approved > carrier invalid orders =  1359
carrier > delivery invalid orders =  23

In [164]:
#Feature engineering(added delivery delay and status cols)

df5['delivery_delay_days']=(df5['order_delivered_customer_date']-df5['order_estimated_delivery_date']).dt.days
df5['delivery_status']=np.select(
    [
        df5['delivery_delay_days']<0,
        df5['delivery_delay_days']==0,
        df5['delivery_delay_days']>0
    ],
    [
        'Early',
        'On time',
        'Late'
    ],
    default=None
)
df5.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay,delivery_delay_days,delivery_status
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,-8.0,-8.0,Early
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,-6.0,-6.0,Early
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,-18.0,-18.0,Early
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,-13.0,-13.0,Early
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,-10.0,-10.0,Early

# **Order Items Table**

In [96]:
#data
df6=pd.read_csv('olist_order_items_dataset.csv')

In [97]:
#size
df6.shape

(112650, 7)

In [98]:
#Analysing
df6.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [99]:
#Null values
df6.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [100]:
#Duplicates
df6.duplicated().sum()

np.int64(0)

In [102]:
#Data type checking
df6.dtypes

order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

In [104]:
#changing shipping_limit_date col data type from obj to datetime
df6['shipping_limit_date']=pd.to_datetime(df6['shipping_limit_date'])

In [105]:
#checking again
df6.dtypes

order_id                       object
order_item_id                   int64
product_id                     object
seller_id                      object
shipping_limit_date    datetime64[ns]
price                         float64
freight_value                 float64
dtype: object

In [172]:
#referetial integrity checking-checking the order ids in order items table is in orders table
missing_ids=df6[~df6['order_id'].isin(df5['order_id'])]
missing_ids

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []

In [109]:
#checcking price have -ve values
df6[df6['price']<=0]

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []

In [111]:
#checking freight values as -ve
df6[df6['freight_value']<0]

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []

# **Reviews Table**

In [112]:
#data
df7=pd.read_csv('olist_order_reviews_dataset.csv')

In [113]:
#Analysing
df7.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [114]:
#size
df7.shape

(99224, 7)

In [173]:
#duplicates acc to review id
df7['review_id'].duplicated().sum()
#in olist datset documentation they mentioned that the same review id is given for diff order ids

np.int64(814)

In [128]:
#checking duplicates acc to order id
df7['order_id'].duplicated().sum()
#one order id can give multiple reviews

np.int64(551)

In [127]:
#review id+order id is primary key
df7[['review_id','order_id']].duplicated().sum()

np.int64(0)

In [130]:
#changing dat type to datetime for date cols
df7['review_creation_date']=pd.to_datetime(df7['review_creation_date'])
df7['review_answer_timestamp']=pd.to_datetime(df7['review_answer_timestamp'])

In [131]:
#checking again the datatype
df7.dtypes

review_id                          object
order_id                           object
review_score                        int64
review_comment_title               object
review_comment_message             object
review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

# **Products Table**

In [132]:
#data
df8=pd.read_csv('olist_products_dataset.csv')

In [133]:
#size
df8.shape

(32951, 9)

In [134]:
#Analysing
df8.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [135]:
#data type
df8.dtypes

product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [136]:
#Null values
df8.isnull().sum()
#we have 610 null values for product_category_name,product_name_lenght,product_description_lenght,product_photos_qty ...may be all are same

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [174]:
#checking whether that 610 records are in order items table so that they are purchased so they are valid no need to remove them
missing=df8[df8['product_category_name'].isna()]['product_id']
df6[df6['product_id'].isin(missing)]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
123,0046e1d57f4c07c8c92ab26be8c3dfc0,1,ff6caf9340512b8bf6d2a2a6df032cfa,38e6dada03429a47197d5d584d793b41,2017-10-02 15:49:17,7.79,7.78
125,00482f2670787292280e0a8153d82467,1,a9c404971d1a5b1cbc2e4070e02731fd,702835e4b785b67a084280efca355756,2017-02-17 16:18:07,7.60,10.96
132,004f5d8f238e8908e6864b874eda3391,1,5a848e4ab52fd5445cdc07aab1c40e48,c826c40d7b19f62a09e2d7c5e7295ee2,2018-03-06 09:29:25,122.99,15.61
142,0057199db02d1a5ef41bacbf41f8f63b,1,41eee23c25f7a574dfaf8d5c151dbb12,e5a3438891c0bfdb9394643f95273d8e,2018-01-25 09:07:51,20.30,16.79
171,006cb7cafc99b29548d4f412c7f9f493,1,e10758160da97891c2fdcbc35f0f031d,323ce52b5b81df2cd804b017b7f09aa7,2018-02-22 13:35:28,56.00,14.14
...,...,...,...,...,...,...,...
112306,ff24fec69b7f3d30f9dc1ab3aee7c179,1,5a848e4ab52fd5445cdc07aab1c40e48,c826c40d7b19f62a09e2d7c5e7295ee2,2018-02-01 02:40:12,122.99,15.61
112333,ff3024474be86400847879103757d1fd,1,f9b1795281ce51b1cf39ef6d101ae8ab,3771c85bac139d2344864ede5d9341e3,2017-11-21 03:55:39,39.90,9.94
112350,ff3a45ee744a7c1f8096d2e72c1a23e4,1,b61d1388a17e3f547d2bc218df02335b,07017df32dc5f2f1d2801e579548d620,2017-05-10 10:15:19,139.00,21.42
112438,ff7b636282b98e0aa524264b295ed928,1,431df35e52c10451171d8037482eeb43,6cd68b3ed6d59aaa9fece558ad360c0a,2018-02-22 15:35:35,49.90,15.11
112501,ffa5e4c604dea4f0a59d19cc2322ac19,2,bd421826916d3e1d445cb860cea3c0fb,59cd88080b93f3c18508673122d26169,2017-12-11 08:41:20,29.99,15.10

In [141]:
#duplicates
df8['product_id'].duplicated().sum()

np.int64(0)

# **Product Transalation Table**

In [143]:
#data
df9=pd.read_csv('product_category_name_translation.csv')

In [144]:
#Analysing
df9.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [145]:
#Null values
df9.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [147]:
#Duplicates
df9['product_category_name'].duplicated().sum()

np.int64(0)